### ISSUE TITLE
Prediction issue

### ISSUE THREAD

**Issue by octoma** [crypto-code/Stock-Market-AI-GUI#2]
I'm using Anaconda environment. I'm running into the following issues:

Simulation 1:
Internal Server Error: /predict_stock/PFE/6mo/1/30
Traceback (most recent call last):
  File "/home/sage/anaconda3/envs/stockstat-1/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sage/anaconda3/envs/stockstat-1/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sage/Desktop/stockstat1/Stock/views.py", line 33, in stock_predict
    data = predict_stock(symbol, period, sim, future)
  File "/home/sage/Desktop/stockstat1/Stock/backend/predict.py", line 179, in predict_stock
    results.append(forecast())
  File "/home/sage/Desktop/stockstat1/Stock/backend/predict.py", line 95, in forecast
    modelnn = Model(
  File "/home/sage/Desktop/stockstat1/Stock/backend/predict.py", line 57, in __init__
    rnn_cells = tf.nn.rnn_cell.MultiRNNCell(
AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'rnn_cell'
[19/Jan/2021 14:04:36] "GET /predict_stock/PFE/6mo/1/30 HTTP/1.1" 500 83765

**Comment by crypto-code** [comment]
The code I had written uses Tensorflow version 1.15.0. You are seeing the error since the you are using Tensorflow  v2.

I would advise you to create an environment with Tensorflow version 1.15.0, which would be the easier way to deal with the error.

An alternative solution would be to migrate your code from v1 to v2, by adding the following lines in all the python files present in the backend folder.
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
I hope this helps you, and thank you for using my project :)

**Comment by octoma** [comment]
Thanks. I downgraded the TensorFlow, and it works perfectly now.
