### ISSUE TITLE
TypeError: 'module' object is not iterable

### ISSUE THREAD

**Issue by 678GUY** [crypto-code/Stock-Market-AI-GUI#3]
I have been trying to get this program to run but I'm having a problem, i keep getting an error in django which breaks everything, i tried to downgrade to version 2.2.6 but that didn't help either

```
M:\Downloads\Stock-Market-AI-GUI-master>python36 manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "M:\pythons\3.6\lib\site-packages\django\urls\resolvers.py", line 591, in url_patterns
    iter(patterns)
TypeError: 'module' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "M:\pythons\3.6\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "M:\pythons\3.6\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "M:\pythons\3.6\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "M:\pythons\3.6\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "M:\pythons\3.6\lib\site-packages\django\core\management\base.py", line 396, in check
    databases=databases,
  File "M:\pythons\3.6\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "M:\pythons\3.6\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "M:\pythons\3.6\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "M:\pythons\3.6\lib\site-packages\django\urls\resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "M:\pythons\3.6\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "M:\pythons\3.6\lib\site-packages\django\urls\resolvers.py", line 598, in url_patterns
    raise ImproperlyConfigured(msg.format(name=self.urlconf_name)) from e
django.core.exceptions.ImproperlyConfigured: The included URLconf 'StockMarket.urls' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.
```

**Comment by crypto-code** [comment]
Don't downgrade Django, it should be higher than v3. When I wrote this project, I used Django version 3.1.5. Try installing that and it should work :)

**Comment by 678GUY** [comment]
i uninstalled it and installed the 3.1.5 version and I'm still having the same issue

```
M:\Downloads\Stock-Market-AI-GUI-master>python36 manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "M:\pythons\3.6\lib\site-packages\django\urls\resolvers.py", line 591, in url_patterns
    iter(patterns)
TypeError: 'module' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "M:\pythons\3.6\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "M:\pythons\3.6\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "M:\pythons\3.6\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "M:\pythons\3.6\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "M:\pythons\3.6\lib\site-packages\django\core\management\base.py", line 396, in check
    databases=databases,
  File "M:\pythons\3.6\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "M:\pythons\3.6\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "M:\pythons\3.6\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "M:\pythons\3.6\lib\site-packages\django\urls\resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "M:\pythons\3.6\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "M:\pythons\3.6\lib\site-packages\django\urls\resolvers.py", line 598, in url_patterns
    raise ImproperlyConfigured(msg.format(name=self.urlconf_name)) from e
django.core.exceptions.ImproperlyConfigured: The included URLconf 'StockMarket.urls' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.
```

**Comment by crypto-code** [comment]
Have you made any modifications to the **urls.py** file ? It looks like the **urlpattern** was modified. Check your urls.py in the **Stock** folder and the **StockMarket** folder, and ensure that it says 

`urlpatterns = [
..........
]`

According to the error it seems like it has been changed to url_patterns. I hope this fixes the error :)

**Comment by 678GUY** [comment]
both of the urls.py files are unmodified, here's their copy paste, you can see there's no _ in urlpattern

```
"""StockMarket URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Stock.urls"))
]

```

```
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("stock", views.stock, name="stock"),
    path("predict", views.predict, name="predict"),
    path("predict_stock/<str:symbol>/<str:period>/<int:sim>/<int:future>", views.stock_predict, name="predict_stock"),
    path("trade", views.trade, name="trade"),
    path("trade_stock/<str:symbol>/<str:period>/<int:init>/<int:skip>", views.stock_trade, name="trade_stock")
]

```

**Comment by crypto-code** [comment]
Have you made any other changes to the project ? I am unable to reproduce your error. I cloned the repository and ran the server with no errors. If you have made any changes, let me know so I can try to reproduce the error to fix it.

**Comment by 678GUY** [comment]
i havent made any change, i suspect something with my python or dependencies isn't right but im not sure

**Comment by crypto-code** [comment]
I will add a **requirements.txt** file as soon as possible. Give me an hour or so, I have a class now.

**Comment by crypto-code** [comment]
I have added the **requirements.txt** as well as an **environment.yml** file (to use if you are working with Anaconda which I recommend) to the root of the repository.

To create new Anaconda environment with the file:
`conda env create -f environment.yml`

**Comment by 678GUY** [comment]
i installed anaconda, opened it and run the commend to make a new environment then tried to install the requirements and i keep getting this error (out of anaconda too), probably because I'm on windows

```
(base) M:\Downloads\Stock-Market-AI-GUI-master>pip install -r requirements.txt
Collecting absl-py==0.11.0
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Requirement already satisfied: alabaster==0.7.12 in m:\users\gay\anaconda3\lib\site-packages (from -r requirements.txt (line 2)) (0.7.12)
Requirement already satisfied: anaconda-client==1.7.2 in m:\users\gay\anaconda3\lib\site-packages (from -r requirements.txt (line 3)) (1.7.2)
Requirement already satisfied: anaconda-project==0.8.3 in m:\users\gay\anaconda3\lib\site-packages (from -r requirements.txt (line 4)) (0.8.3)
Collecting applaunchservices==0.2.1
  Downloading applaunchservices-0.2.1-py3-none-any.whl (6.1 kB)
Collecting appnope==0.1.0
  Downloading appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
Processing m:\opt\concourse\worker\volumes\live\91c8994f-17d8-4d72-71d5-86defaef485b\volume\appscript_1594840169383\work
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'M:\\opt\\concourse\\worker\\volumes\\live\\91c8994f-17d8-4d72-71d5-86defaef485b\\volume\\appscript_1594840169383\\work'
```

**Comment by crypto-code** [comment]
Instead of installing it into the base environment, try creating an environment with the dependencies installed on creation.
Run the following line:
`conda env create -f environment.yml`

This should practically give you a clone environment like mine.

**Comment by 678GUY** [comment]
i managed to get it working manually with anaconda but not with your file, trying to import it gives me a ResolvePackageNotFound error, but still thanks!

**Comment by crypto-code** [comment]
I didn't write the code with GPU support and it's using Tensorflow v1.15. So GPU supported version should be installed separately with 
`pip install tensorflow-gpu==1.15`

Refer to this for details: https://www.tensorflow.org/install/gpu

**Comment by 678GUY** [comment]
i did do it like that i just had other errors (which i managed to fix), thx for the help! also 1 question before you close this, are you gonna update this? because its pretty cool

**Comment by crypto-code** [comment]
Thank you, I hope you enjoy using it :)

I plan to update this project to tensorflow v2 and add GPU support during my summer vacations, currently I am a little busy with university classes.

**Comment by z3nth10n** [comment]
If anybody wants the fixed .yml file:

```yml
name: myenv
channels:
  - defaults
dependencies:
  - alabaster=0.7.12=py36_0
  - anaconda=2020.07=py36_0
  - anaconda-client=1.7.2=py36_0
  - anaconda-project=0.8.4=py_0
  - applaunchservices=0.2.1=py_0
  - argh=0.26.2=py36_0
  - asn1crypto=1.3.0=py36_0
  - astroid=2.4.2=py36_0
  - atomicwrites=1.4.0=py_0
  - attrs=19.3.0=py_0
  - autopep8=1.5.3=py_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=py_0
  - backports=1.0=py_2
  - backports.shutil_get_terminal_size=1.0.0=py36_2
  - beautifulsoup4=4.9.1=py36_0
  - bkcharts=0.2=py36_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - bokeh=2.1.1=py36_0
  - boto=2.49.0=py36_0
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py36_0
  - chardet=3.0.4=py36_1003
  - click=7.1.2=py_0
  - cloudpickle=1.5.0=py_0
  - clyent=1.2.2=py36_1
  - colorama=0.4.3=py_0
  - contextlib2=0.6.0.post1=py_0
  - contextvars=2.4=py_0
  - dask=2.20.0=py_0
  - dask-core=2.20.0=py_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20200713=py_0
  - distributed=2.20.0=py36_0
  - docutils=0.16=py36_1
  - entrypoints=0.3=py36_0
  - et_xmlfile=1.0.1=py_1001
  - filelock=3.0.12=py_0
  - flake8=3.8.3=py_0
  - flask=1.1.2=py_0
  - fsspec=0.7.4=py_0
  - future=0.18.2=py36_1
  - glob2=0.7=py_0
  - heapdict=1.0.1=py_0
  - html5lib=1.1=py_0
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.7.0=py36_0
  - importlib_metadata=1.7.0=0
  - intervaltree=3.0.2=py_1
  - ipykernel=5.3.2=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36_0
  - itsdangerous=1.1.0=py36_0
  - jdcal=1.4.1=py_0
  - jedi=0.17.1=py36_0
  - jinja2=2.11.2=py_0
  - joblib=0.16.0=py_0
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py36_0
  - jupyterlab=2.1.5=py_0
  - jupyterlab_server=1.2.0=py_0
  - keyring=21.2.1=py36_0
  - mccabe=0.6.1=py36_1
  - mock=4.0.2=py_0
  - more-itertools=8.4.0=py_0
  - mpmath=1.1.0=py36_0
  - multipledispatch=0.6.0=py36_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.7=py_0
  - networkx=2.4=py_1
  - nltk=3.5=py_0
  - nose=1.3.7=py36_2
  - notebook=6.0.3=py36_0
  - numpydoc=1.1.0=py_0
  - olefile=0.46=py36_0
  - openpyxl=3.0.4=py_0
  - packaging=20.4=py_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - path=13.1.0=py36_0
  - path.py=12.4.0=0
  - pathlib2=2.3.5=py36_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py36_0
  - pep8=1.7.1=py36_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=20.1.1=py36_1
  - pkginfo=1.5.0.1=py36_0
  - pluggy=0.13.1=py36_0
  - ply=3.11=py36_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - py=1.9.0=py_0
  - pycodestyle=2.6.0=py_0
  - pycparser=2.20=py_2
  - pydocstyle=5.0.2=py_0
  - pyflakes=2.2.0=py_0
  - pygments=2.6.1=py_0
  - pylint=2.5.3=py36_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py36_0
  - pytest=5.4.3=py36_0
  - python=3.6.10
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.4=py_1
  - python-language-server=0.34.1=py36_0
  - python-libarchive-c=2.9=py_0
  - pytz=2020.1=py_0
  - qdarkstyle=2.8.1=py_0
  - qtawesome=0.7.2=py_0
  - qtconsole=4.7.5=py_0
  - qtpy=1.9.0=py_0
  - requests=2.24.0=py_0
  - rope=0.17.0=py_0
  - seaborn=0.10.1=py_0
  - send2trash=1.5.0=py36_0
  - setuptools=49.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - six=1.15.0=py_0
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.2.1=py_0
  - sortedcontainers=2.2.2=py_0
  - soupsieve=2.0.1=py_0
  - sphinx=3.1.2=py_0
  - sphinxcontrib=1.0=py36_1
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sphinxcontrib-websupport=1.2.3=py_0
  - spyder=4.1.4=py36_0
  - spyder-kernels=1.9.2=py36_0
  - sympy=1.6.1=py36_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - toml=0.10.1=py_0
  - toolz=0.10.0=py_0
  - tqdm=4.47.0=py_0
  - traitlets=4.3.3=py36_0
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py36_1
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xlrd=1.2.0=py36_0
  - xlsxwriter=1.2.9=py_0
  - xlwings=0.19.5=py36_0
  - yapf=0.30.0=py_0
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zope=1.0=py36_1
  - zope.event=4.4=py36_0
  - pip:
    - absl-py==0.11.0
    - asgiref==3.3.1
    - astor==0.8.1
    - django==3.1.5
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.33.2
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.3.3
    - mpld3==0.5.2
    - multitasking==0.0.9
    - opencv-python==4.4.0.46
    - opt-einsum==3.3.0
    - pandas-datareader==0.9.0
    - pillow==5.0.0
    - protobuf==3.14.0
    - scipy==1.0.1
    - sqlparse==0.4.1
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - yfinance==0.1.55
prefix: /Users/atinsaki/miniconda3/envs/myenv
```
